Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -2,9 +2,9 @@ name: Docker Image CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ 'main' ]
   pull_request:
-    branches: [ "main" ]
+    branches: [ 'main' ]
   release:
     types: [published]
 
@@ -18,6 +18,13 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+      - name: Check tag matches package version in DESCRIPTION
+        if: github.event_name == 'release'
+        run: |
+          pkg_version="$(grep -P '^Version: \d+\.\d+\.\d+$' DESCRIPTION | cut -d' ' -f2)"
+          echo "pkg_version: $pkg_version"
+          test -n "$pkg_version" || (echo "'Version:' not found in DESCRIPTION" && false)
+          test "v$pkg_version" = ${{ github.ref }} || (echo "'Version:' in DESCRIPTION does not match current git tag" && false)
       - name: Debug
         run: |
           echo "github.ref -> ${{ github.ref }}"
@@ -44,19 +51,11 @@ jobs:
       - name: Docker meta
         id: meta
         uses: docker/metadata-action@v5
-        with:
-          # list of Docker images to use as base name for tags
+        with:          
           images: ${{ env.IMAGE }}
-          # generate Docker tags based on the following events/attributes
           tags: |
             type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
             type=semver,pattern={{version}}
-            # type=semver,pattern={{major}}.{{minor}}
-            # type=semver,pattern={{major}}
-            # type=schedule
-            # type=ref,event=branch
-            # type=ref,event=pr
-            # type=sha
       - name: Build and push
         uses: docker/build-push-action@v5
         with:
